### ISSUE TITLE
Registrar: linked filter returns contacts that do not have this status

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1004]
/registrar/contacts

![image](https://user-images.githubusercontent.com/7734747/46539432-20d5ee80-c8bf-11e8-9665-f1c5aea7e334.png)

![image](https://user-images.githubusercontent.com/7734747/46539483-4105ad80-c8bf-11e8-886a-ea03abf3b498.png)

it also returns the ones that have linked status.

**Comment by artur-beljajev** [comment]
For accurate answer I'd need to see how contact object looks like in a database, but based on investigation I've done, I guess search results from your screenshot are correct, the problem lies in contact status representation.

There is some magic happening there: https://github.com/internetee/registry/blob/b6ecae6a35168f98adf0ed448a26b6c31cf1c579/app/models/contact.rb#L270.

First, both `OK` and `Linked` statuses are removed. Then, `Linked` status is added _only_ if a contact is really used, based on records from a database (you call this "dynamic status", but in fact there isn't such status, it's just a method call). So basically both statuses from `contacts.statuses` DB column are ignored, and get calculated on the fly before displaying.

**Comment by vohmar** [comment]
correct. The contacts do have linked statuses in DB although in reality the dynamic value is correct and these contacts do not have any associacionts with any domains.

**Comment by artur-beljajev** [comment]
Check #956.

**Comment by vohmar** [comment]
fixed by #1552 1552
