### ISSUE TITLE
Registrar API contacts endpoint

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1580]
Part of #1408.

**Comment by maciej-szlosarczyk** [comment]
The principal idea here is to instead of developing a completely new functionality, decouple existing EPP business logic from XML parser, and then re-use the same one in both places. 

First step is to check if it is possible to do so by implementing contact update functionality in REPP on the basis of existing EPP. If that suceeds, we can continue filling in another functionality.
