### ISSUE TITLE
Refactore domain_contacts

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1630]
Domain_contacts table holds relations between domain objects and admin and technical contacts. The table is neede due to many-to-many relations between contact and domain objects.

The table it self has some unnecessary details in it that in some cases can be confusing holding outdated info like in case of automatically created objects and relations in domain transfer.

Minimum set of data for this table is id, domain_id, contact_id, type. Some added value comes from created_at datetime and creator_str to identify who or what created the record. The logic of the latter to should be reviewed as it seems that the value of these not always references the creation of that particular record but might some times reference to the old record in case of domain transfer

Value of other columns like updated_at, updater_str, contact_code_cache, legacy_domain_id, legacy_contact_id is questionable

Additional idea for some extra value could be link or pointer to the epp_log entry that the record is related to.

**Comment by yulgolem** [comment]
1. updated_at, updater_str - standard ActiveRecord update timestamp & PaperTrail gem whodunnit. Left as is.
1. contact_code_cache - used in Domain model to have Admin/Tech Contacts assigned only once per type for a domain. We got some witty custom validators (https://github.com/internetee/registry/blob/master/app/validators/uniqueness_multi_validator.rb) here, so in order to have same validation mechanism used in contact assignment as in nameservers etc I suggest to be left as is.
1. legacy_domain_id, legacy_contact_id - FRED's legacy fields, left as is for backward compatibility.

**Comment by vohmar** [comment]
case closed
