### ISSUE TITLE
Payment processing bug - nil registrar

### ISSUE THREAD

**Issue by yulgolem** [internetee/registry#1991]
Logs - https://gist.github.com/ratM1n/5d6bfa76926aa33f1f1975f06a582958

**Comment by vohmar** [comment]
there are all kind of payments made to that account not only the payments by registrars to top up their credit accounts but also action payments, card payments from registrar and auction portals. But in this case the cause is probably a bank transfer by a auction winner that did not have valid payment card nor could we provide bank link option for their home bank - so they requester an option to transfer the funds.
