### ISSUE TITLE
Additional statuses are removed along with force delete

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registry#2091]
The functionality at a given time works like this: if you set the status, then add the force delete, then the status that was before the force delete is saved, and if you remove the force delete, the status will return.

But, if you put force delete, then add another status, and then remove force delete, the status is deleted. 

Now the question is, is this expected? because this question I do not remember being raised, although such situations in theory could exist.

**Comment by vohmar** [comment]
Removing forceDelete should only remove the statuses set on applying force delete and nothing else - so any statuses that were there before setting FD should remain in place so as the additional statuses set while forceDelete was set. In case of automatically set statuses its not really a big issue if removing forceDelete removes those as scheduled tasks will reset the status at the next run (ie expire or release). We rarely set any statuses manually, removing those could be a problem , but its a rare case and so the issue is low priority
