### ISSUE TITLE
Check domain expiration logic

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#238]
domain is set as expired when timpestamp now > valid to
domain is set on hold (removed from zone) when timestamp now > outzone at
domain is set as delete candidate and random delete time is calculated when timestamp now > delete at
domain is deleted if domain has delete candidate status set

extracted from #235

**Comment by vohmar** [comment]
@teadur please have a quick code review https://github.com/internetee/registry/compare/master...registry-238?expand=1 especially are tests OK

**Comment by vohmar** [comment]
@artur-beljajev https://github.com/internetee/registry/compare/master...registry-238?expand=1#diff-26556a08a299ddd06db8192756a22566R14 registered? is very bad usage of terminology as expired domains are also registered. It is preferable to avoid this kind of checks and test if a domain is expired (instead of "is it not expired"). But if this check is necessary rename registered? to not_expired - more descriptive and correct in domain terminology.

**Comment by vohmar** [comment]
branch deleted
