### ISSUE TITLE
Update "certificates" readme

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#263]
- "crl_path" config key from application.yml is mentioned in "certificates" readme, but it is not used anywhere. The following info should be put instead:

crl_dir: '/home/registry/registry/shared/ca/crl'

- Update -example files

**Comment by teadur** [comment]
actualy crl_path defines where crl file is, it is generated by openssl when you revoke certificates.
It's used in apache/openssl config not directly by our software at the moment.
In future we should make sure that crl file gets updated when cert is revoked/maybe show revoked certs?, because of that  we should keep the variable there.

**Comment by artur-beljajev** [comment]
Well, production code must be working. If some config key is not used now, it should not be there. Or at least it must be somehow marked as unused (say with a comment).
