### ISSUE TITLE
GUI: hide postal address data of the contact objects

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#290]
If system is configured with ignoring postal addresses the options to add this data should be hidden from the portal for registrars and epp web client

**portal for registrars:**
* /registrar/contacts/new
* /registrar/contacts/_CONTACT:ID_

in the info view it might be a good idea to replace the address box with contacts box that would include email and phone number as well so it is a matter of hiding unwanted data instead of the whole data area.

**epp web client:**
as the web client does not have access to server settings it is not possible to make addr fileds dynamic. But to support leaving postall address data blank some changes are still necessary. Please also solve this ticket:
https://github.com/internetee/EPP-web-client/issues/15

**Comment by artur-beljajev** [comment]
#9 is required as well.

**Comment by vohmar** [comment]
updated the description on the part of web-client. Added reference to very lightly related ticket internetee/EPP-web-client#15

**Comment by artur-beljajev** [comment]
"in the info view it might be a good idea to replace the address box with contacts box that would include email and phone number as well so it is a matter of hiding unwanted data instead of the whole data area."

There isn't much benefit of extracting only 2 fields into separate section. I think it is anyway a matter of separate ticket, if any change is needed.

**Comment by vohmar** [comment]
in production, branch deleted, ticket closed
