### ISSUE TITLE
Directo: directos.request empty for credit invoices

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#344]
registry saves the XML sent to directo in the directos.request column. It has values only for monthly invoices, for credit loading invoices it is empty.

**Comment by artur-beljajev** [comment]
Why Directo requests are saved?

**Comment by vohmar** [comment]
we also have log everything policy (we log every request coming in or going out from the registry). This is mainly for debugging, problem solving and proving what was sent out from the registry in case there is some doubt.

**Comment by artur-beljajev** [comment]
@vohmar FYI: It is actually vice-versa: monthly invoice requests are not saved

**Comment by artur-beljajev** [comment]
See #509

**Comment by artur-beljajev** [comment]
@vohmar What do you think, if instead of that "directos" and any other possible table we create some single audit log table and collect there everything that is really important for us to log (who did what and when)?

We could store, for example:
- Who/what initiated the action: user email, name, IP; background job name
- Time when the event has occured
- Human-readable description

Communication with third-party services like Directo and Äriregister might also be logged there.
+ some simple UI for all that

Worth noting: I don't suggest this as a replacement for application log (Rails.logger, syslog as a backend on prod). That part remains as is for now. It is more like a high-level audit log. Some kind of activity log.
Whereas application log will continue acting as a kind of exception catcher.
Both "epp_logs" and "repp_logs" are actually about the same: it is kind of audit log (I haven't done deep analysis or those tables, so please correct me if I am wrong).

I don't think creating a new storage (=table) for every new thing that needs to leave some trail is a good idea.

**Comment by vohmar** [comment]
lets continue with directos for now and come back to this question with "papertrail"/"log and versioning" refactoring. There are two separate types of "logs" - versioning and action logs. These should be handled together if we change anything.
