### ISSUE TITLE
Change "registrant_url" setting

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#380]
I find using "registrant_url" setting's name in the code misleading, since one may thing that this is a url of registrant, which is incorrect. I would change it to "registrant_area_url".

**Comment by teadur** [comment]
What would be url of a registrant ?

**Comment by artur-beljajev** [comment]
As an example http://prntscr.com/ebxtl3, but it is not relevant. What really matters, is that the app has a concept of registrant. There are "Registrant" model, "registrars" controller, routes and so on.

**Comment by teadur** [comment]
But registrant model doesnot have any url related parameter, actualy it doesnot even make any sense to have url related to registrant i cant quite understand why something that doesnot make any sense would confuze you.

But if you must change it i would go for registrant_portal_url rather then registrant_area_url, because we call it registrant portal, not registrant area.

**Comment by artur-beljajev** [comment]
See #1151
