### ISSUE TITLE
Update phone nr validation for contacts

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#386]
on contact:create and contact:update the added phone number should be validated against having all zero values in country code or phone number part

**Comment by artur-beljajev** [comment]
№ 1: I have discovered the following issue while testing EPP update: I created new contact with the code "test". Then I tried to update it by specifying "test" as a content of "id" tag, but it failed, since given id is always converted to uppercase ("TEST" in this case) before querying DB (app/controllers/epp/contacts_controller.rb:85). I studied EPP standards, but was unable to find anything concerning letter case. I wonder if we can remove that auto-conversion to keep things simple and avoid unexpected results, like this case.

spec/requests/epp/contact/update/phone_spec.rb

№ 2: Should I manually update EPP docs/examples?

**Comment by vohmar** [comment]
No1. EPP and XML schemas are case sensitive so to avoid any confusion we intentionally enforced all capital object IDs. So until registrars are not complaining about this we have no reason to change this.

No2. No this all zero validation case is not worth the time of manually updating examples. We'll update the doc for this edge case when we have new automatic update solution.

**Comment by artur-beljajev** [comment]
№ 1: Do registrars always send upper-case ids?

**Comment by teadur** [comment]
The last part seems to be blocked by #387

**Comment by vohmar** [comment]
in production
