### ISSUE TITLE
Refactor models/directo.rb

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#509]
- Consider extracting Directo into separate gem
- Enable accounting software easy switch
- AccountActivity > AccountEntry

#205 

API spec
http://wiki.directo.ee/et/xmlcore

**Comment by artur-beljajev** [comment]
@vohmar if we extract it to a gem, what is the benefit we get? Is there any chance that we will use Directo in other apps?

**Comment by vohmar** [comment]
as an open source project we try to avoid .ee specific features  - interface with Directo is one example of such functionality. We should design the software so that any one, including us, could easily develop interface/adapter to their preferred accounting solution. Directo solutions could be used as an example. Currently only registry project interfaces with accounting software. If the solution is easily applicable we could consider direct interfaces from regsitrars' and auction portals/applications for example.

**Comment by artur-beljajev** [comment]
Add `zones.accounting_code`

**Comment by artur-beljajev** [comment]
Add "Copy code" button to new registrar

**Comment by artur-beljajev** [comment]
Log request xml, response, time

**Comment by artur-beljajev** [comment]
It will be needed to set zone accounting codes in admin right after the release.

**Comment by artur-beljajev** [comment]
@teadur @ratM1n `bank_transactions.in_directo` is absent in both staging and prod. It should be manually remove in other envs.

**Comment by artur-beljajev** [comment]
@vohmar Do we really need that "copy registrar code to accounting customer code" button in new registrar view? It may not worth the effort if we add new registrars twice a year.

**Comment by vohmar** [comment]
we will not do the button, directo handle field will continue to be separately entered.

**Comment by artur-beljajev** [comment]
`"Unit" => "tk",` which we send to Directo is not listed in the spec we got from Directo's representative

**Comment by vohmar** [comment]
it looks like unit is undocumented feature as it is sent to directo and invoice records all have it correctly set in Directo.

**Comment by vohmar** [comment]
the gem has to log all the requests including the xmls sent out, responses from directo and system generated messages like errors, warnings, info messages

**Comment by artur-beljajev** [comment]
Fill "VATCode" with registrar VAT number if present
