### ISSUE TITLE
Keep track of sent emails

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#549]
- Separate database (api_log?)
- Save text version body
- Metadata to save:
  - Time
  - Recipient
  - Associated object (domain, contact)
- UI in admin area
  - Filtering or sorting? What columns?

https://github.com/rails/rails/blob/ee35b79d4cff24b960be54c3f5c4f46627c069fe/actionmailer/lib/action_mailer/log_subscriber.rb#L8

**Comment by artur-beljajev** [comment]
@martin or @teadur Do you think it's still needed to send mail-related events to syslog once we have this ticket done?

**Comment by artur-beljajev** [comment]
@vohmar Please provide your requirements regarding metadata (3rd list item) in comments

**Comment by vohmar** [comment]
* date and time the email was sent
* recipient(s)
* define events or email types to save instead of the full subject - makes it easier to search ie 'email update', 'registrant change: confirmation', 'expire', 'force delete'

also there should be an answer from the recipient mail server - whether the sending was successful or not and why (no domain, do mailserver, no address, quota full etc)

**Comment by vohmar** [comment]
need a view in admin to track the statuses of sent out automatic emails (automatic emails include: expire messages, registrant change messages, registrant email update messages, domain delete confirmation messages, forcedelete messages

**Comment by vohmar** [comment]
the email server keeps track of all the emails sent out except the rwhois contact messages sent to the registrant - these go out through Amazon SMS to catch bouncing emails. There is no option to access the logs through admin, but considering the rare occasions where these info is needed its not worth the effort at this time.
