### ISSUE TITLE
WHOIS: domain data is not updated on pendig status removal

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#757]
When pending status (pendingUpdate, pendingDeleteConfirmation) is removed from domain whois update is not triggered and domain data in whois is not updated

might apply to other status changes as well.

**Comment by maciej-szlosarczyk** [comment]
Possible to reproduce this issue only for `pendingUpdate`, `PendingDelete` does update the Whois Record.

**Comment by maciej-szlosarczyk** [comment]
During the investigation of this issue I discovered the following:

`DomainUpdateConfirmJob` and `clean_expired_pendings` cron job share the same behaviour. When pending statuses are removed (i.e `pendingDeleteConfirmation`), we are not executing callbacks (such as updating whois records) or updating the timestamps on the domain records, but we're still retaining a Papertrail log of the changes in domain object. 

Is that the expected behaviour, @vohmar?

**Comment by vohmar** [comment]
@maciej-szlosarczyk in general this seems to be the cause of the problem - updating domain registrant by requiring confirmation has special status related - updatePending. Setting this status calls for whois update and results in status being displayed publicly in whois. So endind this update process either by expiry, denial or acceptance by the current registrant must call for whois data update to remove the status and update other data if necessary.

**Comment by maciej-szlosarczyk** [comment]
@vohmar I made the required changes. Aside from the buggy scenario with `pendingUpdate`, please also test the `clean_expired_pendings` Domain cronjob to ensure that there are no unwanted side-effects there.

**Comment by vohmar** [comment]
in production
