### ISSUE TITLE
Registrant API

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#902]
Registrant portal works currently on read only copy of registry db, but as we have requirements for new functionality to write back to registry we need to switch to using API. As the logic in this case is user not registrar based we should create dedicated API for registrant portal.

Required functionality
* query domain list using ident (must support ident code array as we also query the domains of the companies that the user is management board member of) - Fixed in #922 
* domain info - identical to RestEPP query - Fixed in #922 
* contact info - identical to RestEPP query - Fixed in PR #928
* contact update - updating contact data has following restrictions
  * it is limited to phone nr, email address and postal address (in case postal address processing is enabled)
  * user can update data of only their own contact object (ie registrant of a domain cannot update contacts of admin or tech contact of that domain if these are different persons)
  * admin contacts of a domain registered to a company (ident type = org) can update contact details of that contact object as well
* registry lock - registrant (incl board members) and admin contact of a domain can lock (and unlock) the domain for updates by registrar and registrant - fixed in #927 
---
* registrar info - up for consideration as the data is there in the domain info response - separate query might not be necessary

Tasks: 

1. 1st task is to set the API architecture including authorisation/authentication
2. document queries so that web developers can start with portal development
3. develop tests and API

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, a couple of questions:

- do we have a versioning scheme in place for this API? Since our registrar api is V1, should this be V2?
- Will it be publicly available or is it an API only used by the new registrant portal? Can I, as a registrant just make a HTTPS request and query my domain list through this API? That would change at least a bit how we authenticate the requests.
---
I'll split it into multiple tickets, as probably all of the endpoints can be tested and deployed separately.

**Comment by vohmar** [comment]
* as this is separate api i think this should be v1 as well.
* the use of this api should at least in the beginning be limited to the registrant portal only.
